# Generated by Django 5.0.2 on 2024-05-03 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports2', '0002_report_cat_two_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report_cat_two',
            name='category',
            field=models.CharField(default='cat2', max_length=20),
        ),
    ]
