# Generated by Django 5.0.2 on 2024-02-17 22:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_user_is_verified_delete_onetimepassword'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='email',
        ),
        migrations.AddField(
            model_name='user',
            name='email_or_phone',
            field=models.CharField(default='', max_length=255, unique=True, validators=[django.core.validators.RegexValidator(message='Enter a valid email address or phone number.', regex='^[a-zA-Z0-9+_.-]+@[a-zA-Z0-9.-]+$|^[\\d\\-\\+\\(\\) ]+$')], verbose_name='Email Address or Phone Number'),
            preserve_default=False,
        ),
    ]
