# Generated by Django 5.0.2 on 2024-06-23 19:30

import django.core.files.storage
import pathlib
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='photo',
            field=models.ImageField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(location=pathlib.PureWindowsPath('C:/Users/Mohammed Elsayaed/env1/media')), upload_to='user_photos/', verbose_name='Profile Picture'),
        ),
    ]
