# Generated by Django 5.0.2 on 2024-07-01 01:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_admin_last_login'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='admin',
            name='last_login',
        ),
    ]
