# Generated by Django 5.0.2 on 2024-07-05 23:39

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_remove_admin_last_login'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='photo',
            field=models.ImageField(blank=True, null=True, storage=accounts.models.get_firebase_storage, upload_to='user_photos/', verbose_name='Profile Picture'),
        ),
    ]
