# Generated by Django 5.0.2 on 2024-04-01 09:38

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_problem_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='image',
            field=models.ImageField(storage=django.core.files.storage.FileSystemStorage(location='media'), upload_to='reports/'),
        ),
    ]
