# Generated by Django 5.0.2 on 2024-07-01 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_alter_report_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='category',
            field=models.CharField(choices=[('Environmental', 'env'), ('Road', 'road'), ('Electric', 'elec'), ('other', 'Other')], max_length=20),
        ),
    ]
