# Generated by Django 5.0.2 on 2024-07-05 23:39

import reports.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0003_alter_report_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='image',
            field=models.ImageField(storage=reports.models.get_firebase_storage, upload_to='reports/'),
        ),
    ]
