# Generated by Django 5.0.2 on 2024-05-13 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0006_alter_report_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='category',
            field=models.CharField(choices=[('Environmental', 'env'), ('Traffic', 'tr'), ('Electric', 'elec'), ('other', 'Other')], max_length=20),
        ),
    ]
